name: Test CI for skeleton

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Print a message to confirm GitHub Actions is working
      - name: Test GitHub Actions
        run: echo "Working"